name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - jschenke488
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug in detail
    validations:
      required: true
  - type: textarea
    id: expected-output
    attributes:
      label: What did you expect to happen?
      description: Also tell us, what did you expect to happen?
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How do you reproduce this issue?
      description: What do you need to do for this bug to occur?
    validations:
      required: false
