blank_issues_enabled: false
contact_links:
  - name: HauC3 Discord
    url: https://discord.gg/dW89J7V
    about: If you need to get in direct contact with us or are reporting an exploit, ask on the Discord server.
